[book]
authors = ["David"]
language = "zh"
multilingual = false
src = "src"
title = "Engineering a Compiler"

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/CnTransGroup/EngineeringACompiler"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true